name: 'Terraform Apply'

on:
  workflow_dispatch:

jobs:
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # Init Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Import alert source if it already exists
      - name: Import alert source if it exists
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
          TF_VAR_incident_lead_user_id: ${{ secrets.INCIDENT_LEAD_USER_ID }}
          TF_VAR_incident_manager_user_id: ${{ secrets.INCIDENT_MANAGER_USER_ID }}
          TF_VAR_incident_releng_team_id: ${{ secrets.INCIDENT_RELENG_TEAM_ID }}
        run: |
          ALERT_ID=$(curl -s -H "Authorization: Bearer $INCIDENT_API_KEY" https://api.incident.io/v2/alert_sources | jq -r '.alert_sources[] | select(.name=="LF Releng Alerts") | .id')
          if [ -n "$ALERT_ID" ]; then
            echo "Alert source exists with ID: $ALERT_ID. Importing..."
            terraform import 'incident_alert_source.releng' $ALERT_ID || true
          else
            echo "No existing alert source found. Proceeding to create."
          fi

      # Import escalation path if it already exists
      - name: Import escalation path if it exists
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
          TF_VAR_incident_lead_user_id: ${{ secrets.INCIDENT_LEAD_USER_ID }}
          TF_VAR_incident_manager_user_id: ${{ secrets.INCIDENT_MANAGER_USER_ID }}
          TF_VAR_incident_releng_team_id: ${{ secrets.INCIDENT_RELENG_TEAM_ID }}
        run: |
          ESCALATION_ID=$(curl -s -H "Authorization: Bearer $INCIDENT_API_KEY" https://api.incident.io/v2/escalation_paths | jq -r '.escalation_paths[] | select(.name=="Release Engineering") | .id')
          if [ -n "$ESCALATION_ID" ]; then
            echo "Escalation path exists with ID: $ESCALATION_ID. Importing..."
            terraform import 'incident_escalation_path.releng' $ESCALATION_ID || true
          else
            echo "No existing escalation path found. Proceeding to create."
          fi

      # Import workflow if it already exists
      - name: Import workflow if it exists
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
          TF_VAR_incident_lead_user_id: ${{ secrets.INCIDENT_LEAD_USER_ID }}
          TF_VAR_incident_manager_user_id: ${{ secrets.INCIDENT_MANAGER_USER_ID }}
          TF_VAR_incident_releng_team_id: ${{ secrets.INCIDENT_RELENG_TEAM_ID }}
        run: |
          WORKFLOW_ID=$(curl -s -H "Authorization: Bearer $INCIDENT_API_KEY" https://api.incident.io/v2/workflows | jq -r '.workflows[] | select(.name=="Release Engineering Default Workflow (TF Managed)") | .id')
          if [ -n "$WORKFLOW_ID" ]; then
            echo "Workflow exists with ID: $WORKFLOW_ID. Importing..."
            terraform import 'incident_workflow.releng_default_workflow' $WORKFLOW_ID || true
          else
            echo "No existing workflow found. Proceeding to create."
          fi

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
          TF_VAR_incident_lead_user_id: ${{ secrets.INCIDENT_LEAD_USER_ID }}
          TF_VAR_incident_manager_user_id: ${{ secrets.INCIDENT_MANAGER_USER_ID }}
          TF_VAR_incident_releng_team_id: ${{ secrets.INCIDENT_RELENG_TEAM_ID }}
