# Workflow to apply changes to production
name: 'Terraform Apply'

# Requires manual trigger
on:
  workflow_dispatch:

jobs:
  # Define the Terraform Apply job
  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Terraform using a compatible version for Incident.io             
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # Initialize Terraform working directory
      - name: Terraform Init
        id: init
        run: terraform init

      # Apply Terraform changes with manual approval
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          INCIDENT_API_KEY: ${{ secrets.INCIDENT_API_KEY }}
          TF_VAR_incident_lead_user_id: ${{ secrets.INCIDENT_LEAD_USER_ID }}
          TF_VAR_incident_manager_user_id: ${{ secrets.INCIDENT_MANAGER_USER_ID }}
          TF_VAR_incident_releng_team_id: ${{ secrets.INCIDENT_RELENG_TEAM_ID }}
